services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./src:/app/src
      - ./mock_data:/app/mock_data
      - ${SAT_PREDICTOR_OUTPUT_DIR}:/app/satpred_output

    env_file:
      - .env
    environment:
      - IS_DOCKER=True
      - DB_HOST=db
      - DB_PORT=5432
      - OBS_PLANNER_IP=satellite_predictor # network created by compose
      - OBS_PLANNER_PORT=1929
      - SAT_PREDICTOR_OUTPUT_DIR=/app/satpred_output # otherwise main.py variable "LocalOutPath" would break
      - WEAVE_PROJECT_NAME=llm-obs
    depends_on:
      - db
      - satellite_predictor
    command: ["sh", "-c", "wandb login --relogin ${WANDB_API_KEY}  && python -m streamlit run src/app.py --server.port=8501 --server.address=0.0.0.0"]

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - POSTGRES_data:/var/lib/postgresql/data

  satellite_predictor:
    build:
      context: ./obs_planner
      dockerfile: Dockerfile
    environment:
      - LOCAL_UID=${UID}
      - LOCAL_GID=${GID}
    ports:
      - "${OBS_PLANNER_PORT}:1929"
    privileged: true
    volumes:
      - type: bind
        source: "${SAT_PREDICTOR_OUTPUT_DIR}"
        target: /usr/share/SiTech/SatellitePredictor/Output
        read_only: false
        bind:
          create_host_path: false # user must create it manually to avoid permission issues
      - ./obs_planner/src:/observation-planner/src/
      - ./obs_planner/configs:/observation-planner/configs/

volumes:
  POSTGRES_data: