services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./src:/app/src
      #- ${OBS_PLANNER_ROOT}:/app/obs_planner
      - ./mock_data:/app/mock_data
    env_file:
      - .env
    environment:
      - IS_DOCKER=True
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - POSTGRES_data:/var/lib/postgresql/data

volumes:
  POSTGRES_data: