services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - ./src:/app/src
      - ${OBS_PLANNER_ROOT}:/obs_planner
    environment:
      - ENV
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - IS_DOCKER=True
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - POSTGRES_data:/var/lib/postgresql/data

volumes:
  POSTGRES_data: