from sqlalchemy import Column, Integer, String, Float, Boolean
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()

class Observation(Base):
    __tablename__ = 'observations'

    obsid = Column(Integer, primary_key=True)
    designation = Column(String, nullable=False)
    prep_time = Column(String, nullable=False)
    start_time = Column(String, nullable=False)
    end_time = Column(String, nullable=False)
    pa = Column(Float)
    too = Column(Boolean, nullable=False)
    telescope = Column(String, nullable=False)
    dither = Column(Boolean, nullable=False)
    tle_line0 = Column(String)
    tle_line1 = Column(String)
    tle_line2 = Column(String)
    eph_flag = Column(Integer, nullable=False)
    ra_deg = Column(Float)
    dec_deg = Column(Float)
    ra_rate = Column(Float)
    dec_rate = Column(Float)
    az_deg = Column(Float)
    el_deg = Column(Float)
    az_rate = Column(Float)
    el_rate = Column(Float)
    sid_track_flag = Column(Boolean)
    exp_time = Column(String)
    notes = Column(String)
    filter = Column(String)
    focus_prior = Column(Boolean)
    delay_after = Column(String)
    bin_value = Column(String)
    organization = Column(String)
    username = Column(String)
    user_unique_id = Column(String)
    user_project = Column(String)  
    exposures = Column(Integer)  
    priority = Column(Integer)
